### ISSUE TITLE
Missing Pipe greater than and lower than

### ISSUE THREAD

**Issue by CarstenK1** [leohoe/karabiner-pc-qwertz#1]
Seems Pipe and greater than and lower than is missing

**Comment by leohoe** [comment]
Pipe (|), greater than (>) and lower than (<) work fine on the integrated macbook keyboard, and the apple magic keyboard I'm using.

Weirdly, I've noticed an issue specifically on non-Apple QWERTZ USB keyboards: for some ungodly reason, it seems to completely switch the < (i.e. the key next to left shift) and ^ (i.e. the key below ESC) keys, on that keyboard only. 

Do you have the same issue? Can you type pipe, gt and lt on your "^" key?

**Comment by leohoe** [comment]
(Also, thank you very much for your input! I hope I can find a way to fix this for you, without breaking it on the keyboard my employer has me use...)

**Comment by CarstenK1** [comment]
@leohoe yep exactly ...I'm using a non-Apple QWERTZ Keyboard. By the way good job mapping the keys 👍 I don't have to think about how the apple keyboard works.

**Comment by leohoe** [comment]
Haha, that's the goal! Thank you, I'm glad it's of help!

**Comment by leohoe** [comment]
@CarstenK1 I have added new rules that should fix this issue:

- "PC-Style German Alt Gr (pipe - compatible with switched < and ^ keys)" (keep this one ABOVE the next two rules)
- "Change Caret to Less Than"
- "Change Less Than to Caret"

This works on my non-Mac USB keyboard - could you please let me know if it fixes the issue for you as well?

**Comment by junedev** [comment]
Works like a charm, I think this issue can be closed. 🙂

**Comment by Nekkowe** [comment]
Great, thank you for letting me know!

**Comment by leohoe** [comment]
Great, thank you for letting me know! :sparkles:
